"""empty message

Revision ID: 57dbc8386438
Revises: 1ee2ea7deb5a
Create Date: 2022-08-20 11:15:55.951184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57dbc8386438'
down_revision = '1ee2ea7deb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'seeking_venue',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'seeking_venue',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
