"""empty message

Revision ID: 5aabd96938d3
Revises: b4602df92623
Create Date: 2022-08-20 09:46:46.143049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aabd96938d3'
down_revision = 'b4602df92623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venues_city_id_fkey', 'venues', type_='foreignkey')
    op.drop_column('venues', 'city_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('venues_city_id_fkey', 'venues', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###
