"""empty message

Revision ID: 7c3566f32a58
Revises: 4fb9e908ee8b
Create Date: 2022-08-21 17:17:45.118928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3566f32a58'
down_revision = '4fb9e908ee8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('is_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'is_done')
    # ### end Alembic commands ###
