"""empty message

Revision ID: a92dcad896e1
Revises: 0b8c699fbf97
Create Date: 2022-08-20 11:18:30.541946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92dcad896e1'
down_revision = '0b8c699fbf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
