"""empty message

Revision ID: b243c4d1bc50
Revises: 7232950e81af
Create Date: 2022-08-19 23:40:32.645587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b243c4d1bc50'
down_revision = '7232950e81af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venues', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venues', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'city_id')
    op.drop_table('cities')
    # ### end Alembic commands ###
