"""empty message

Revision ID: b4602df92623
Revises: b243c4d1bc50
Create Date: 2022-08-20 02:12:41.419877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4602df92623'
down_revision = 'b243c4d1bc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('venues', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('venues', 'num_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'seeking_talent')
    # ### end Alembic commands ###
