"""empty message

Revision ID: b5ce9a0ded57
Revises: 1372251bbc98
Create Date: 2022-08-24 20:13:04.901259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ce9a0ded57'
down_revision = '1372251bbc98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'is_done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
